//Generated by gopages from src/index.ghtml, do not edit
//This file will be overwritten during build

package pages

import(
	"io"
	"http"
	"fmt"
	"os"
 )
func Render(context WebContext){
                                        print := func(toPrint ...interface{}){

                                        }

                                        formValue := func(keyToGet string) string{
                                                return context.GetParams()[keyToGet]
                                        }
                                        print(""); formValue("")// prevent initialization runtime error
			%!(EXTRA string=)context.WriteString(`<html>
        <body>
        `)
 print("<h1>Hello World</h1>") 
context.WriteString(`
        </body>
 </html>
`)


}
