//Generated by gopages from src/index.ghtml, do not edit
//This file will be overwritten during build

package pages

import(
	"fmt"
	"os"
	"http"
	"log"

)

type WebContext interface {
    WriteString(content string)
    GetParams()map[string]string
}

func Render(context WebContext){
					print := func(toPrint ...interface{}){
						context.WriteString( fmt.Sprint(toPrint))
					}

					formValue := func(keyToGet string) string{
                                                return context.GetParams()[keyToGet]
                                        }
					print(""); formValue("")// prevent initialization runtime error

			context.WriteString( `<html>
        <body>
        `)
 print("<h1>Hello World</h1>")
context.WriteString( `
        </body>
 </html>
`)


}
func Run(address string) (err os.Error){
                                                println("gopages serving on", address)
						//err = context.GetParams()[address]
						err = http.ListenAndServe(address, nil)
						if err !=nil{
							log.Fatal("ListenAndServe: ", err.String())
						}
						 //err = context.GetParams(address, nil)
                                                return
}

