//Generated by gopages from src/index.ghtml, do not edit
//This file will be overwritten during build

package pages

import(
	"io"
//	"http"
	"fmt"
)
func Render(context WebContext){
					print := func(toPrint ...interface{}){
						context.WriteString( fmt.Sprint(toPrint))
					}

					formValue := func(keyToGet string) string{
                                                return context.GetParams()[keyToGet]
                                        }
					print(""); formValue("")// prevent initialization runtime error

			context.WriteString( `<html>
       <body>
        `)
 print("<h1>Hello World Watashi wa Santi Desu.</h1>") 
io.WriteString(context, `
        </body>
 </html>
`)


}
